import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import "./globals.css";

import logo from "@/app/assets/logo-api.png"
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-pallete02`}>

        <Header op1={"primeira-rota"} op2={"segunda-rota"}/>

        <div className="w-full flex justify-center h-[580px] items-center flex-col p-[20px]">
          <Image  className="h-auto w-[800px]" src={logo} alt="ue"/>
          <h1 className="text-pallete04 font-bold text-[50px]">Prova :)</h1>
        </div>

        {children}
      </body>
    </html>
  );
}
